name: dashcast_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_router: ^0.0.1
  cupertino_icons: ^1.0.0
  dashcast_server:
    path: ../dashcast_server
  flutter_sound: ^7.5.0
  google_fonts: ^1.1.0
  http: ^0.12.0
  intl: ^0.16.0
  path: ^1.7.0
  url_launcher: ^5.7.0
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
