name: dashcast_server
description: The server for the DashCast v2 sample app

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  shelf: ^0.7.5
  json_annotation: any

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: any
  json_serializable: any
